# Generated by Django 5.2 on 2026-01-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
